// Code generated by Arduino IoT Cloud, DO NOT EDIT.
#pragma once

#include <Arduino.h>
#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

#include "secrets.h"

const char DEVICE_LOGIN_NAME[]  = "a1fa7208-51cd-4315-954f-789c7a47e580";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password


int numUnlocks;
int numWrongAttempts;
bool isLocked;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(numUnlocks, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(numWrongAttempts, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(isLocked, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
